// <auto-generated />
using System;
using DoAnCuoiKi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnCuoiKi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221215132023_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnCuoiKi.Data.Brand", b =>
                {
                    b.Property<int?>("brandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("brandId"));

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("brandId");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            brandId = 1,
                            isDelete = false,
                            name = "ASUS"
                        },
                        new
                        {
                            brandId = 2,
                            isDelete = false,
                            name = "GIGABYTE"
                        },
                        new
                        {
                            brandId = 3,
                            isDelete = false,
                            name = "MSI"
                        },
                        new
                        {
                            brandId = 4,
                            isDelete = false,
                            name = "Asrock"
                        },
                        new
                        {
                            brandId = 5,
                            isDelete = false,
                            name = "Intel"
                        },
                        new
                        {
                            brandId = 6,
                            isDelete = false,
                            name = "Samsung"
                        },
                        new
                        {
                            brandId = 7,
                            isDelete = false,
                            name = "Apacer"
                        },
                        new
                        {
                            brandId = 8,
                            isDelete = false,
                            name = "Kingston"
                        },
                        new
                        {
                            brandId = 9,
                            isDelete = false,
                            name = "Kingmax"
                        },
                        new
                        {
                            brandId = 10,
                            isDelete = false,
                            name = "Sony"
                        },
                        new
                        {
                            brandId = 11,
                            isDelete = false,
                            name = "JBL"
                        },
                        new
                        {
                            brandId = 12,
                            isDelete = false,
                            name = "Sennheiser"
                        },
                        new
                        {
                            brandId = 13,
                            isDelete = false,
                            name = "Corsair"
                        },
                        new
                        {
                            brandId = 14,
                            isDelete = false,
                            name = "Logitech"
                        },
                        new
                        {
                            brandId = 15,
                            isDelete = false,
                            name = "Apple"
                        });
                });

            modelBuilder.Entity("DoAnCuoiKi.Data.Cart", b =>
                {
                    b.Property<int?>("cartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("cartId"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("cartId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("DoAnCuoiKi.Data.Category", b =>
                {
                    b.Property<int?>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("categoryId"));

                    b.Property<bool?>("isDelete")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            isDelete = false,
                            name = "Chuột - bàn phím"
                        },
                        new
                        {
                            categoryId = 2,
                            isDelete = false,
                            name = "Thiết bị âm thanh"
                        },
                        new
                        {
                            categoryId = 3,
                            isDelete = false,
                            name = "Linh kiện PC - Laptop"
                        },
                        new
                        {
                            categoryId = 4,
                            isDelete = false,
                            name = "SSD"
                        },
                        new
                        {
                            categoryId = 5,
                            isDelete = false,
                            name = "HDD"
                        },
                        new
                        {
                            categoryId = 6,
                            isDelete = false,
                            name = "Ram máy tính"
                        },
                        new
                        {
                            categoryId = 7,
                            isDelete = false,
                            name = "Ổ cứng di động"
                        },
                        new
                        {
                            categoryId = 8,
                            isDelete = false,
                            name = "Ổ cứng SSD di động"
                        },
                        new
                        {
                            categoryId = 9,
                            isDelete = false,
                            name = "Thẻ nhớ"
                        },
                        new
                        {
                            categoryId = 10,
                            isDelete = false,
                            name = "USB"
                        });
                });

            modelBuilder.Entity("DoAnCuoiKi.Data.Order", b =>
                {
                    b.Property<int?>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("orderId"));

                    b.Property<string>("customerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateReceive")
                        .HasColumnType("datetime2");

                    b.Property<string>("otherInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<double>("totalPrice")
                        .HasColumnType("float");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("orderId");

                    b.HasIndex("userId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("DoAnCuoiKi.Data.OrderDetails", b =>
                {
                    b.Property<int?>("orderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("orderDetailsId"));

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.Property<int>("productAmout")
                        .HasColumnType("int");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("productPrice")
                        .HasColumnType("float");

                    b.Property<double>("totalPrice")
                        .HasColumnType("float");

                    b.HasKey("orderDetailsId");

                    b.HasIndex("orderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("DoAnCuoiKi.Data.Product", b =>
                {
                    b.Property<int?>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("productId"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<int>("brandId")
                        .HasColumnType("int");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("productId");

                    b.HasIndex("brandId");

                    b.HasIndex("categoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("DoAnCuoiKi.Data.User", b =>
                {
                    b.Property<int?>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("userId"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            address = "VN",
                            email = "admin@gmail.com",
                            gender = "Nam",
                            isDelete = false,
                            name = "admin",
                            password = "123123",
                            phone = "0338786222",
                            role = "Admin"
                        });
                });

            modelBuilder.Entity("DoAnCuoiKi.Data.Cart", b =>
                {
                    b.HasOne("DoAnCuoiKi.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCuoiKi.Data.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DoAnCuoiKi.Data.Order", b =>
                {
                    b.HasOne("DoAnCuoiKi.Data.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("DoAnCuoiKi.Data.OrderDetails", b =>
                {
                    b.HasOne("DoAnCuoiKi.Data.Order", "order")
                        .WithMany()
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");
                });

            modelBuilder.Entity("DoAnCuoiKi.Data.Product", b =>
                {
                    b.HasOne("DoAnCuoiKi.Data.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCuoiKi.Data.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }
}
